// src/config/apiConfig.js

/**
 * Centralized API configuration.
 * Replace any value wrapped in [REPLACE_*] based on Swagger documentation.
 */

const resolveReplaceable = (rawValue, fallbackValue) => {
  if (!rawValue) {
    return fallbackValue;
  }

  // Keep [REPLACE_*] markers in the file, but fall back at runtime.
  if (rawValue.startsWith("[REPLACE_")) {
    return fallbackValue;
  }

  return rawValue;
};

// ================================
// BASE URL & GLOBAL SETTINGS
// ================================
export const RAW_API_BASE_URL = "[REPLACE_API_BASE_URL]";
// NOTE: Using CRA proxy in development. Set REACT_APP_API_BASE_URL for production.
export const DEFAULT_API_BASE_URL = "";
export const API_BASE_URL = resolveReplaceable(
  process.env.REACT_APP_API_BASE_URL || RAW_API_BASE_URL,
  DEFAULT_API_BASE_URL
);

export const REQUEST_TIMEOUT_MS = 30000;
export const WITH_CREDENTIALS = false;

// ================================
// AUTH ENDPOINTS
// ================================
export const RAW_AUTH_BASE_PATH = "[REPLACE_AUTH_BASE_PATH]";
export const DEFAULT_AUTH_BASE_PATH = "/auth";
export const AUTH_BASE_PATH = resolveReplaceable(
  RAW_AUTH_BASE_PATH,
  DEFAULT_AUTH_BASE_PATH
);

export const RAW_AUTH_LOGIN_PATH = "[REPLACE_AUTH_LOGIN_PATH]";
export const DEFAULT_AUTH_LOGIN_PATH = `${AUTH_BASE_PATH}/login`;
export const AUTH_LOGIN_PATH = resolveReplaceable(
  RAW_AUTH_LOGIN_PATH,
  DEFAULT_AUTH_LOGIN_PATH
);

export const RAW_AUTH_REGISTER_PATH = "[REPLACE_AUTH_REGISTER_PATH]";
export const DEFAULT_AUTH_REGISTER_PATH = `${AUTH_BASE_PATH}/register`;
export const AUTH_REGISTER_PATH = resolveReplaceable(
  RAW_AUTH_REGISTER_PATH,
  DEFAULT_AUTH_REGISTER_PATH
);

export const RAW_AUTH_LOGOUT_PATH = "[REPLACE_AUTH_LOGOUT_PATH]";
export const DEFAULT_AUTH_LOGOUT_PATH = `${AUTH_BASE_PATH}/logout`;
export const AUTH_LOGOUT_PATH = resolveReplaceable(
  RAW_AUTH_LOGOUT_PATH,
  DEFAULT_AUTH_LOGOUT_PATH
);

export const RAW_AUTH_ME_PATH = "[REPLACE_AUTH_ME_PATH]";
export const DEFAULT_AUTH_ME_PATH = `${AUTH_BASE_PATH}/me`;
export const AUTH_ME_PATH = resolveReplaceable(
  RAW_AUTH_ME_PATH,
  DEFAULT_AUTH_ME_PATH
);

// ================================
// FIELD MAPPINGS
// ================================
export const FIELD_MAP = {
  // TODO: Replace with actual request field names from Swagger.
  LOGIN_USERNAME_FIELD: "[REPLACE_LOGIN_USERNAME_FIELD]",
  LOGIN_PASSWORD_FIELD: "[REPLACE_LOGIN_PASSWORD_FIELD]",
  REGISTER_USERNAME_FIELD: "[REPLACE_REGISTER_USERNAME_FIELD]",
  REGISTER_PASSWORD_FIELD: "[REPLACE_REGISTER_PASSWORD_FIELD]",

  // TODO: Replace with actual user identifier fields from Swagger.
  CURRENT_USER_ID_FIELD: "[REPLACE_CURRENT_USER_ID_FIELD]",
  CURRENT_USER_NAME_FIELD: "[REPLACE_CURRENT_USER_NAME_FIELD]",
};

export const DEFAULT_FIELD_FALLBACKS = {
  LOGIN_USERNAME_FIELD: "username",
  LOGIN_PASSWORD_FIELD: "password",
  REGISTER_USERNAME_FIELD: "username",
  REGISTER_PASSWORD_FIELD: "password",
  CURRENT_USER_ID_FIELD: "id",
  CURRENT_USER_NAME_FIELD: "name",
};

// ================================
// TOKEN & AUTH HEADER SETTINGS
// ================================
export const RAW_AUTH_HEADER_NAME = "[REPLACE_AUTH_HEADER_NAME]";
export const DEFAULT_AUTH_HEADER_NAME = "Authorization";
export const AUTH_HEADER_NAME = resolveReplaceable(
  RAW_AUTH_HEADER_NAME,
  DEFAULT_AUTH_HEADER_NAME
);

export const RAW_AUTH_TOKEN_PREFIX = "[REPLACE_AUTH_TOKEN_PREFIX]";
export const DEFAULT_AUTH_TOKEN_PREFIX = "Bearer";
export const AUTH_TOKEN_PREFIX = resolveReplaceable(
  RAW_AUTH_TOKEN_PREFIX,
  DEFAULT_AUTH_TOKEN_PREFIX
);

export const RAW_AUTH_TOKEN_STORAGE_KEY = "[REPLACE_AUTH_TOKEN_STORAGE_KEY]";
export const DEFAULT_AUTH_TOKEN_STORAGE_KEY = "auth_token";
export const AUTH_TOKEN_STORAGE_KEY = resolveReplaceable(
  RAW_AUTH_TOKEN_STORAGE_KEY,
  DEFAULT_AUTH_TOKEN_STORAGE_KEY
);

export const TOKEN_FIELD_CANDIDATES = [
  "[REPLACE_TOKEN_FIELD_PRIMARY]",
  "[REPLACE_TOKEN_FIELD_SECONDARY]",
  "accessToken",
  "token",
  "jwt",
];

// ================================
// RESPONSE NORMALIZATION
// ================================
export const DATA_WRAPPER_CANDIDATES = [
  "[REPLACE_DATA_WRAPPER_PRIMARY]",
  "[REPLACE_DATA_WRAPPER_SECONDARY]",
  "data",
  "result",
  "payload",
];

export const ERROR_MESSAGE_FIELD_CANDIDATES = [
  "[REPLACE_ERROR_MESSAGE_FIELD_PRIMARY]",
  "[REPLACE_ERROR_MESSAGE_FIELD_SECONDARY]",
  "message",
  "error",
  "detail",
];

export const ERROR_LIST_FIELD_CANDIDATES = [
  "[REPLACE_ERROR_LIST_FIELD_PRIMARY]",
  "[REPLACE_ERROR_LIST_FIELD_SECONDARY]",
  "errors",
  "violations",
];

const BASE_ENDPOINTS = {
  AUTH: {
    BASE_PATH: AUTH_BASE_PATH,
    LOGIN: AUTH_LOGIN_PATH,
    REGISTER: AUTH_REGISTER_PATH,
    LOGOUT: AUTH_LOGOUT_PATH,
    ME: AUTH_ME_PATH,
  },
  // TODO: Add more endpoint groups (PROPERTIES, BOOKINGS, etc.)
  // Keep [REPLACE_*] markers until Swagger schemas are available.
};

// ================================
// USER ENDPOINTS
// ================================
export const RAW_USER_BASE_PATH = "[REPLACE_USER_BASE_PATH]";
export const DEFAULT_USER_BASE_PATH = "/hpms/api/User";
export const USER_BASE_PATH = resolveReplaceable(
  RAW_USER_BASE_PATH,
  DEFAULT_USER_BASE_PATH
);

export const RAW_USER_POST_PATH = "[REPLACE_USER_POST_PATH]";
export const DEFAULT_USER_POST_PATH = `${USER_BASE_PATH}/Post`;
export const USER_POST_PATH = resolveReplaceable(
  RAW_USER_POST_PATH,
  DEFAULT_USER_POST_PATH
);

export const RAW_USER_GET_PATH = "[REPLACE_USER_GET_PATH]";
export const DEFAULT_USER_GET_PATH = `${USER_BASE_PATH}/Get`;
export const USER_GET_PATH = resolveReplaceable(
  RAW_USER_GET_PATH,
  DEFAULT_USER_GET_PATH
);

export const RAW_USER_GET_BY_ID_PATH = "[REPLACE_USER_GET_BY_ID_PATH]";
export const DEFAULT_USER_GET_BY_ID_PATH = `${USER_BASE_PATH}/GetById`;
export const USER_GET_BY_ID_PATH = resolveReplaceable(
  RAW_USER_GET_BY_ID_PATH,
  DEFAULT_USER_GET_BY_ID_PATH
);

export const RAW_USER_GET_LIST_PATH = "[REPLACE_USER_GET_LIST_PATH]";
export const DEFAULT_USER_GET_LIST_PATH = `${USER_BASE_PATH}/GetList`;
export const USER_GET_LIST_PATH = resolveReplaceable(
  RAW_USER_GET_LIST_PATH,
  DEFAULT_USER_GET_LIST_PATH
);

export const RAW_USER_PUT_PATH = "[REPLACE_USER_PUT_PATH]";
export const DEFAULT_USER_PUT_PATH = `${USER_BASE_PATH}/Put`;
export const USER_PUT_PATH = resolveReplaceable(
  RAW_USER_PUT_PATH,
  DEFAULT_USER_PUT_PATH
);

export const RAW_USER_ACCESS_TOKEN_PATH = "[REPLACE_USER_ACCESS_TOKEN_PATH]";
export const DEFAULT_USER_ACCESS_TOKEN_PATH = `${USER_BASE_PATH}/GetAccessToken`;
export const USER_ACCESS_TOKEN_PATH = resolveReplaceable(
  RAW_USER_ACCESS_TOKEN_PATH,
  DEFAULT_USER_ACCESS_TOKEN_PATH
);

// ================================
// LANGUAGE HEADER SETTINGS
// ================================
export const RAW_ACCEPT_LANGUAGE_HEADER = "[REPLACE_ACCEPT_LANGUAGE_HEADER]";
export const DEFAULT_ACCEPT_LANGUAGE_HEADER = "Accept-Language";
export const ACCEPT_LANGUAGE_HEADER = resolveReplaceable(
  RAW_ACCEPT_LANGUAGE_HEADER,
  DEFAULT_ACCEPT_LANGUAGE_HEADER
);

export const RAW_DEFAULT_LANGUAGE = "[REPLACE_DEFAULT_LANGUAGE]";
export const DEFAULT_DEFAULT_LANGUAGE = "en";
export const DEFAULT_LANGUAGE = resolveReplaceable(
  RAW_DEFAULT_LANGUAGE,
  DEFAULT_DEFAULT_LANGUAGE
);

export const USERS_ENDPOINTS = {
  BASE_PATH: USER_BASE_PATH,
  GET: USER_GET_PATH,
  GET_BY_ID: USER_GET_BY_ID_PATH,
  GET_LIST: USER_GET_LIST_PATH,
  POST: USER_POST_PATH,
  PUT: USER_PUT_PATH,
  ACCESS_TOKEN: USER_ACCESS_TOKEN_PATH,
};

// ================================
// GUEST ENDPOINTS
// ================================
export const RAW_GUEST_BASE_PATH = "[REPLACE_GUEST_BASE_PATH]";
export const DEFAULT_GUEST_BASE_PATH = "/hpms/api/Guest";
export const GUEST_BASE_PATH = resolveReplaceable(
  RAW_GUEST_BASE_PATH,
  DEFAULT_GUEST_BASE_PATH
);

export const RAW_GUEST_POST_PATH = "[REPLACE_GUEST_POST_PATH]";
export const DEFAULT_GUEST_POST_PATH = `${GUEST_BASE_PATH}/Post`;
export const GUEST_POST_PATH = resolveReplaceable(
  RAW_GUEST_POST_PATH,
  DEFAULT_GUEST_POST_PATH
);

export const RAW_GUEST_PUT_PATH = "[REPLACE_GUEST_PUT_PATH]";
export const DEFAULT_GUEST_PUT_PATH = `${GUEST_BASE_PATH}/Put`;
export const GUEST_PUT_PATH = resolveReplaceable(
  RAW_GUEST_PUT_PATH,
  DEFAULT_GUEST_PUT_PATH
);

export const RAW_GUEST_DELETE_PATH = "[REPLACE_GUEST_DELETE_PATH]";
export const DEFAULT_GUEST_DELETE_PATH = `${GUEST_BASE_PATH}/Delete`;
export const GUEST_DELETE_PATH = resolveReplaceable(
  RAW_GUEST_DELETE_PATH,
  DEFAULT_GUEST_DELETE_PATH
);

export const RAW_GUEST_GET_LIST_PATH = "[REPLACE_GUEST_GET_LIST_PATH]";
export const DEFAULT_GUEST_GET_LIST_PATH = `${GUEST_BASE_PATH}/GetList`;
export const GUEST_GET_LIST_PATH = resolveReplaceable(
  RAW_GUEST_GET_LIST_PATH,
  DEFAULT_GUEST_GET_LIST_PATH
);

export const GUESTS_ENDPOINTS = {
  BASE_PATH: GUEST_BASE_PATH,
  POST: GUEST_POST_PATH,
  PUT: GUEST_PUT_PATH,
  DELETE: GUEST_DELETE_PATH,
  GET_LIST: GUEST_GET_LIST_PATH,
};

// ================================
// USER ROLE ENDPOINTS
// ================================
export const RAW_USER_ROLE_BASE_PATH = "[REPLACE_USER_ROLE_BASE_PATH]";
export const DEFAULT_USER_ROLE_BASE_PATH = "/hpms/api/UserRole";
export const USER_ROLE_BASE_PATH = resolveReplaceable(
  RAW_USER_ROLE_BASE_PATH,
  DEFAULT_USER_ROLE_BASE_PATH
);

export const RAW_USER_ROLE_POST_PATH = "[REPLACE_USER_ROLE_POST_PATH]";
export const DEFAULT_USER_ROLE_POST_PATH = `${USER_ROLE_BASE_PATH}/Post`;
export const USER_ROLE_POST_PATH = resolveReplaceable(
  RAW_USER_ROLE_POST_PATH,
  DEFAULT_USER_ROLE_POST_PATH
);

export const RAW_USER_ROLE_PUT_PATH = "[REPLACE_USER_ROLE_PUT_PATH]";
export const DEFAULT_USER_ROLE_PUT_PATH = `${USER_ROLE_BASE_PATH}/Put`;
export const USER_ROLE_PUT_PATH = resolveReplaceable(
  RAW_USER_ROLE_PUT_PATH,
  DEFAULT_USER_ROLE_PUT_PATH
);

export const RAW_USER_ROLE_DELETE_PATH = "[REPLACE_USER_ROLE_DELETE_PATH]";
export const DEFAULT_USER_ROLE_DELETE_PATH = `${USER_ROLE_BASE_PATH}/Delete`;
export const USER_ROLE_DELETE_PATH = resolveReplaceable(
  RAW_USER_ROLE_DELETE_PATH,
  DEFAULT_USER_ROLE_DELETE_PATH
);

export const RAW_USER_ROLE_GET_BY_ID_PATH = "[REPLACE_USER_ROLE_GET_BY_ID_PATH]";
export const DEFAULT_USER_ROLE_GET_BY_ID_PATH = `${USER_ROLE_BASE_PATH}/GetById`;
export const USER_ROLE_GET_BY_ID_PATH = resolveReplaceable(
  RAW_USER_ROLE_GET_BY_ID_PATH,
  DEFAULT_USER_ROLE_GET_BY_ID_PATH
);

export const RAW_USER_ROLE_GET_LIST_PATH = "[REPLACE_USER_ROLE_GET_LIST_PATH]";
export const DEFAULT_USER_ROLE_GET_LIST_PATH = `${USER_ROLE_BASE_PATH}/GetList`;
export const USER_ROLE_GET_LIST_PATH = resolveReplaceable(
  RAW_USER_ROLE_GET_LIST_PATH,
  DEFAULT_USER_ROLE_GET_LIST_PATH
);

export const USER_ROLES_ENDPOINTS = {
  BASE_PATH: USER_ROLE_BASE_PATH,
  POST: USER_ROLE_POST_PATH,
  PUT: USER_ROLE_PUT_PATH,
  DELETE: USER_ROLE_DELETE_PATH,
  GET_BY_ID: USER_ROLE_GET_BY_ID_PATH,
  GET_LIST: USER_ROLE_GET_LIST_PATH,
};

// ================================
// ROOM ENDPOINTS
// ================================
export const RAW_ROOM_BASE_PATH = "[REPLACE_ROOM_BASE_PATH]";
export const DEFAULT_ROOM_BASE_PATH = "/hpms/api/Room";
export const ROOM_BASE_PATH = resolveReplaceable(
  RAW_ROOM_BASE_PATH,
  DEFAULT_ROOM_BASE_PATH
);

export const RAW_ROOM_GET_PATH = "[REPLACE_ROOM_GET_PATH]";
export const DEFAULT_ROOM_GET_PATH = `${ROOM_BASE_PATH}/Get`;
export const ROOM_GET_PATH = resolveReplaceable(
  RAW_ROOM_GET_PATH,
  DEFAULT_ROOM_GET_PATH
);

export const RAW_ROOM_GET_LIST_PATH = "[REPLACE_ROOM_GET_LIST_PATH]";
export const DEFAULT_ROOM_GET_LIST_PATH = `${ROOM_BASE_PATH}/GetList`;
export const ROOM_GET_LIST_PATH = resolveReplaceable(
  RAW_ROOM_GET_LIST_PATH,
  DEFAULT_ROOM_GET_LIST_PATH
);

export const RAW_ROOM_POST_PATH = "[REPLACE_ROOM_POST_PATH]";
export const DEFAULT_ROOM_POST_PATH = `${ROOM_BASE_PATH}/Post`;
export const ROOM_POST_PATH = resolveReplaceable(
  RAW_ROOM_POST_PATH,
  DEFAULT_ROOM_POST_PATH
);

export const RAW_ROOM_PUT_PATH = "[REPLACE_ROOM_PUT_PATH]";
export const DEFAULT_ROOM_PUT_PATH = `${ROOM_BASE_PATH}/Put`;
export const ROOM_PUT_PATH = resolveReplaceable(
  RAW_ROOM_PUT_PATH,
  DEFAULT_ROOM_PUT_PATH
);

export const RAW_ROOM_DELETE_PATH = "[REPLACE_ROOM_DELETE_PATH]";
export const DEFAULT_ROOM_DELETE_PATH = `${ROOM_BASE_PATH}/Delete`;
export const ROOM_DELETE_PATH = resolveReplaceable(
  RAW_ROOM_DELETE_PATH,
  DEFAULT_ROOM_DELETE_PATH
);

export const ROOMS_ENDPOINTS = {
  BASE_PATH: ROOM_BASE_PATH,
  GET: ROOM_GET_PATH,
  GET_LIST: ROOM_GET_LIST_PATH,
  POST: ROOM_POST_PATH,
  PUT: ROOM_PUT_PATH,
  DELETE: ROOM_DELETE_PATH,
};

// ================================
// ROOM TYPE ENDPOINTS
// ================================
export const RAW_ROOM_TYPE_BASE_PATH = "[REPLACE_ROOM_TYPE_BASE_PATH]";
export const DEFAULT_ROOM_TYPE_BASE_PATH = "/hpms/api/RoomType";
export const ROOM_TYPE_BASE_PATH = resolveReplaceable(
  RAW_ROOM_TYPE_BASE_PATH,
  DEFAULT_ROOM_TYPE_BASE_PATH
);

export const RAW_ROOM_TYPE_GET_PATH = "[REPLACE_ROOM_TYPE_GET_PATH]";
export const DEFAULT_ROOM_TYPE_GET_PATH = `${ROOM_TYPE_BASE_PATH}/Get`;
export const ROOM_TYPE_GET_PATH = resolveReplaceable(
  RAW_ROOM_TYPE_GET_PATH,
  DEFAULT_ROOM_TYPE_GET_PATH
);

export const RAW_ROOM_TYPE_GET_LIST_PATH = "[REPLACE_ROOM_TYPE_GET_LIST_PATH]";
export const DEFAULT_ROOM_TYPE_GET_LIST_PATH = `${ROOM_TYPE_BASE_PATH}/GetList`;
export const ROOM_TYPE_GET_LIST_PATH = resolveReplaceable(
  RAW_ROOM_TYPE_GET_LIST_PATH,
  DEFAULT_ROOM_TYPE_GET_LIST_PATH
);

export const RAW_ROOM_TYPE_POST_PATH = "[REPLACE_ROOM_TYPE_POST_PATH]";
export const DEFAULT_ROOM_TYPE_POST_PATH = `${ROOM_TYPE_BASE_PATH}/Post`;
export const ROOM_TYPE_POST_PATH = resolveReplaceable(
  RAW_ROOM_TYPE_POST_PATH,
  DEFAULT_ROOM_TYPE_POST_PATH
);

export const RAW_ROOM_TYPE_PUT_PATH = "[REPLACE_ROOM_TYPE_PUT_PATH]";
export const DEFAULT_ROOM_TYPE_PUT_PATH = `${ROOM_TYPE_BASE_PATH}/Put`;
export const ROOM_TYPE_PUT_PATH = resolveReplaceable(
  RAW_ROOM_TYPE_PUT_PATH,
  DEFAULT_ROOM_TYPE_PUT_PATH
);

export const RAW_ROOM_TYPE_DELETE_PATH = "[REPLACE_ROOM_TYPE_DELETE_PATH]";
export const DEFAULT_ROOM_TYPE_DELETE_PATH = `${ROOM_TYPE_BASE_PATH}/Delete`;
export const ROOM_TYPE_DELETE_PATH = resolveReplaceable(
  RAW_ROOM_TYPE_DELETE_PATH,
  DEFAULT_ROOM_TYPE_DELETE_PATH
);

export const ROOM_TYPES_ENDPOINTS = {
  BASE_PATH: ROOM_TYPE_BASE_PATH,
  GET: ROOM_TYPE_GET_PATH,
  GET_LIST: ROOM_TYPE_GET_LIST_PATH,
  POST: ROOM_TYPE_POST_PATH,
  PUT: ROOM_TYPE_PUT_PATH,
  DELETE: ROOM_TYPE_DELETE_PATH,
};

// ================================
// PROPERTY TYPE ENDPOINTS
// ================================
export const RAW_PROPERTY_TYPE_BASE_PATH = "[REPLACE_PROPERTY_TYPE_BASE_PATH]";
export const DEFAULT_PROPERTY_TYPE_BASE_PATH = "/hpms/api/PropertyType";
export const PROPERTY_TYPE_BASE_PATH = resolveReplaceable(
  RAW_PROPERTY_TYPE_BASE_PATH,
  DEFAULT_PROPERTY_TYPE_BASE_PATH
);

export const RAW_PROPERTY_TYPE_POST_PATH = "[REPLACE_PROPERTY_TYPE_POST_PATH]";
export const DEFAULT_PROPERTY_TYPE_POST_PATH = `${PROPERTY_TYPE_BASE_PATH}/Post`;
export const PROPERTY_TYPE_POST_PATH = resolveReplaceable(
  RAW_PROPERTY_TYPE_POST_PATH,
  DEFAULT_PROPERTY_TYPE_POST_PATH
);

export const RAW_PROPERTY_TYPE_PUT_PATH = "[REPLACE_PROPERTY_TYPE_PUT_PATH]";
export const DEFAULT_PROPERTY_TYPE_PUT_PATH = `${PROPERTY_TYPE_BASE_PATH}/Put`;
export const PROPERTY_TYPE_PUT_PATH = resolveReplaceable(
  RAW_PROPERTY_TYPE_PUT_PATH,
  DEFAULT_PROPERTY_TYPE_PUT_PATH
);

export const RAW_PROPERTY_TYPE_DELETE_PATH = "[REPLACE_PROPERTY_TYPE_DELETE_PATH]";
export const DEFAULT_PROPERTY_TYPE_DELETE_PATH = `${PROPERTY_TYPE_BASE_PATH}/Delete`;
export const PROPERTY_TYPE_DELETE_PATH = resolveReplaceable(
  RAW_PROPERTY_TYPE_DELETE_PATH,
  DEFAULT_PROPERTY_TYPE_DELETE_PATH
);

export const RAW_PROPERTY_TYPE_GET_LIST_PATH =
  "[REPLACE_PROPERTY_TYPE_GET_LIST_PATH]";
export const DEFAULT_PROPERTY_TYPE_GET_LIST_PATH = `${PROPERTY_TYPE_BASE_PATH}/GetList`;
export const PROPERTY_TYPE_GET_LIST_PATH = resolveReplaceable(
  RAW_PROPERTY_TYPE_GET_LIST_PATH,
  DEFAULT_PROPERTY_TYPE_GET_LIST_PATH
);

export const PROPERTY_TYPES_ENDPOINTS = {
  BASE_PATH: PROPERTY_TYPE_BASE_PATH,
  POST: PROPERTY_TYPE_POST_PATH,
  PUT: PROPERTY_TYPE_PUT_PATH,
  DELETE: PROPERTY_TYPE_DELETE_PATH,
  GET_LIST: PROPERTY_TYPE_GET_LIST_PATH,
};

// ================================
// PROPERTY ENDPOINTS
// ================================
export const RAW_PROPERTY_BASE_PATH = "[REPLACE_PROPERTY_BASE_PATH]";
export const DEFAULT_PROPERTY_BASE_PATH = "/hpms/api/Property";
export const PROPERTY_BASE_PATH = resolveReplaceable(
  RAW_PROPERTY_BASE_PATH,
  DEFAULT_PROPERTY_BASE_PATH
);

export const RAW_PROPERTY_POST_PATH = "[REPLACE_PROPERTY_POST_PATH]";
export const DEFAULT_PROPERTY_POST_PATH = `${PROPERTY_BASE_PATH}/Post`;
export const PROPERTY_POST_PATH = resolveReplaceable(
  RAW_PROPERTY_POST_PATH,
  DEFAULT_PROPERTY_POST_PATH
);

export const RAW_PROPERTY_PUT_PATH = "[REPLACE_PROPERTY_PUT_PATH]";
export const DEFAULT_PROPERTY_PUT_PATH = `${PROPERTY_BASE_PATH}/Put`;
export const PROPERTY_PUT_PATH = resolveReplaceable(
  RAW_PROPERTY_PUT_PATH,
  DEFAULT_PROPERTY_PUT_PATH
);

export const RAW_PROPERTY_DELETE_PATH = "[REPLACE_PROPERTY_DELETE_PATH]";
export const DEFAULT_PROPERTY_DELETE_PATH = `${PROPERTY_BASE_PATH}/Delete`;
export const PROPERTY_DELETE_PATH = resolveReplaceable(
  RAW_PROPERTY_DELETE_PATH,
  DEFAULT_PROPERTY_DELETE_PATH
);

export const RAW_PROPERTY_GET_LIST_PATH = "[REPLACE_PROPERTY_GET_LIST_PATH]";
export const DEFAULT_PROPERTY_GET_LIST_PATH = `${PROPERTY_BASE_PATH}/GetList`;
export const PROPERTY_GET_LIST_PATH = resolveReplaceable(
  RAW_PROPERTY_GET_LIST_PATH,
  DEFAULT_PROPERTY_GET_LIST_PATH
);

export const RAW_PROPERTY_GET_BY_ID_PATH = "[REPLACE_PROPERTY_GET_BY_ID_PATH]";
export const DEFAULT_PROPERTY_GET_BY_ID_PATH = `${PROPERTY_BASE_PATH}/GetById`;
export const PROPERTY_GET_BY_ID_PATH = resolveReplaceable(
  RAW_PROPERTY_GET_BY_ID_PATH,
  DEFAULT_PROPERTY_GET_BY_ID_PATH
);

export const PROPERTIES_ENDPOINTS = {
  BASE_PATH: PROPERTY_BASE_PATH,
  POST: PROPERTY_POST_PATH,
  PUT: PROPERTY_PUT_PATH,
  DELETE: PROPERTY_DELETE_PATH,
  GET_LIST: PROPERTY_GET_LIST_PATH,
  GET_BY_ID: PROPERTY_GET_BY_ID_PATH,
};

// ================================
// PROPERTY AMENITY ENDPOINTS
// ================================
export const RAW_PROPERTY_AMENITY_BASE_PATH =
  "[REPLACE_PROPERTY_AMENITY_BASE_PATH]";
export const DEFAULT_PROPERTY_AMENITY_BASE_PATH = "/hpms/api/PropertyAmenity";
export const PROPERTY_AMENITY_BASE_PATH = resolveReplaceable(
  RAW_PROPERTY_AMENITY_BASE_PATH,
  DEFAULT_PROPERTY_AMENITY_BASE_PATH
);

export const RAW_PROPERTY_AMENITY_POST_PATH =
  "[REPLACE_PROPERTY_AMENITY_POST_PATH]";
export const DEFAULT_PROPERTY_AMENITY_POST_PATH = `${PROPERTY_AMENITY_BASE_PATH}/Post`;
export const PROPERTY_AMENITY_POST_PATH = resolveReplaceable(
  RAW_PROPERTY_AMENITY_POST_PATH,
  DEFAULT_PROPERTY_AMENITY_POST_PATH
);

export const RAW_PROPERTY_AMENITY_PUT_PATH =
  "[REPLACE_PROPERTY_AMENITY_PUT_PATH]";
export const DEFAULT_PROPERTY_AMENITY_PUT_PATH = `${PROPERTY_AMENITY_BASE_PATH}/Put`;
export const PROPERTY_AMENITY_PUT_PATH = resolveReplaceable(
  RAW_PROPERTY_AMENITY_PUT_PATH,
  DEFAULT_PROPERTY_AMENITY_PUT_PATH
);

export const RAW_PROPERTY_AMENITY_DELETE_PATH =
  "[REPLACE_PROPERTY_AMENITY_DELETE_PATH]";
export const DEFAULT_PROPERTY_AMENITY_DELETE_PATH = `${PROPERTY_AMENITY_BASE_PATH}/Delete`;
export const PROPERTY_AMENITY_DELETE_PATH = resolveReplaceable(
  RAW_PROPERTY_AMENITY_DELETE_PATH,
  DEFAULT_PROPERTY_AMENITY_DELETE_PATH
);

export const RAW_PROPERTY_AMENITY_GET_LIST_PATH =
  "[REPLACE_PROPERTY_AMENITY_GET_LIST_PATH]";
export const DEFAULT_PROPERTY_AMENITY_GET_LIST_PATH = `${PROPERTY_AMENITY_BASE_PATH}/GetList`;
export const PROPERTY_AMENITY_GET_LIST_PATH = resolveReplaceable(
  RAW_PROPERTY_AMENITY_GET_LIST_PATH,
  DEFAULT_PROPERTY_AMENITY_GET_LIST_PATH
);

export const PROPERTY_AMENITIES_ENDPOINTS = {
  BASE_PATH: PROPERTY_AMENITY_BASE_PATH,
  POST: PROPERTY_AMENITY_POST_PATH,
  PUT: PROPERTY_AMENITY_PUT_PATH,
  DELETE: PROPERTY_AMENITY_DELETE_PATH,
  GET_LIST: PROPERTY_AMENITY_GET_LIST_PATH,
};

// ================================
// ROOM AMENITY ENDPOINTS
// ================================
export const RAW_ROOM_AMENITY_BASE_PATH =
  "[REPLACE_ROOM_AMENITY_BASE_PATH]";
export const DEFAULT_ROOM_AMENITY_BASE_PATH = "/hpms/api/RoomAmenity";
export const ROOM_AMENITY_BASE_PATH = resolveReplaceable(
  RAW_ROOM_AMENITY_BASE_PATH,
  DEFAULT_ROOM_AMENITY_BASE_PATH
);

export const RAW_ROOM_AMENITY_POST_PATH =
  "[REPLACE_ROOM_AMENITY_POST_PATH]";
export const DEFAULT_ROOM_AMENITY_POST_PATH = `${ROOM_AMENITY_BASE_PATH}/Post`;
export const ROOM_AMENITY_POST_PATH = resolveReplaceable(
  RAW_ROOM_AMENITY_POST_PATH,
  DEFAULT_ROOM_AMENITY_POST_PATH
);

export const RAW_ROOM_AMENITY_PUT_PATH =
  "[REPLACE_ROOM_AMENITY_PUT_PATH]";
export const DEFAULT_ROOM_AMENITY_PUT_PATH = `${ROOM_AMENITY_BASE_PATH}/Put`;
export const ROOM_AMENITY_PUT_PATH = resolveReplaceable(
  RAW_ROOM_AMENITY_PUT_PATH,
  DEFAULT_ROOM_AMENITY_PUT_PATH
);

export const RAW_ROOM_AMENITY_DELETE_PATH =
  "[REPLACE_ROOM_AMENITY_DELETE_PATH]";
export const DEFAULT_ROOM_AMENITY_DELETE_PATH = `${ROOM_AMENITY_BASE_PATH}/Delete`;
export const ROOM_AMENITY_DELETE_PATH = resolveReplaceable(
  RAW_ROOM_AMENITY_DELETE_PATH,
  DEFAULT_ROOM_AMENITY_DELETE_PATH
);

export const RAW_ROOM_AMENITY_GET_LIST_PATH =
  "[REPLACE_ROOM_AMENITY_GET_LIST_PATH]";
export const DEFAULT_ROOM_AMENITY_GET_LIST_PATH = `${ROOM_AMENITY_BASE_PATH}/GetList`;
export const ROOM_AMENITY_GET_LIST_PATH = resolveReplaceable(
  RAW_ROOM_AMENITY_GET_LIST_PATH,
  DEFAULT_ROOM_AMENITY_GET_LIST_PATH
);

export const RAW_ROOM_AMENITY_GET_BY_ID_PATH =
  "[REPLACE_ROOM_AMENITY_GET_BY_ID_PATH]";
export const DEFAULT_ROOM_AMENITY_GET_BY_ID_PATH = `${ROOM_AMENITY_BASE_PATH}/GetById`;
export const ROOM_AMENITY_GET_BY_ID_PATH = resolveReplaceable(
  RAW_ROOM_AMENITY_GET_BY_ID_PATH,
  DEFAULT_ROOM_AMENITY_GET_BY_ID_PATH
);

export const ROOM_AMENITIES_ENDPOINTS = {
  BASE_PATH: ROOM_AMENITY_BASE_PATH,
  POST: ROOM_AMENITY_POST_PATH,
  PUT: ROOM_AMENITY_PUT_PATH,
  DELETE: ROOM_AMENITY_DELETE_PATH,
  GET_LIST: ROOM_AMENITY_GET_LIST_PATH,
  GET_BY_ID: ROOM_AMENITY_GET_BY_ID_PATH,
};

// ================================
// SEASONAL PRICING ENDPOINTS
// ================================
export const RAW_SEASONAL_PRICING_BASE_PATH =
  "[REPLACE_SEASONAL_PRICING_BASE_PATH]";
export const DEFAULT_SEASONAL_PRICING_BASE_PATH = "/hpms/api/SeasonalPricing";
export const SEASONAL_PRICING_BASE_PATH = resolveReplaceable(
  RAW_SEASONAL_PRICING_BASE_PATH,
  DEFAULT_SEASONAL_PRICING_BASE_PATH
);

export const RAW_SEASONAL_PRICING_POST_PATH =
  "[REPLACE_SEASONAL_PRICING_POST_PATH]";
export const DEFAULT_SEASONAL_PRICING_POST_PATH = `${SEASONAL_PRICING_BASE_PATH}/Post`;
export const SEASONAL_PRICING_POST_PATH = resolveReplaceable(
  RAW_SEASONAL_PRICING_POST_PATH,
  DEFAULT_SEASONAL_PRICING_POST_PATH
);

export const RAW_SEASONAL_PRICING_PUT_PATH =
  "[REPLACE_SEASONAL_PRICING_PUT_PATH]";
export const DEFAULT_SEASONAL_PRICING_PUT_PATH = `${SEASONAL_PRICING_BASE_PATH}/Put`;
export const SEASONAL_PRICING_PUT_PATH = resolveReplaceable(
  RAW_SEASONAL_PRICING_PUT_PATH,
  DEFAULT_SEASONAL_PRICING_PUT_PATH
);

export const RAW_SEASONAL_PRICING_DELETE_PATH =
  "[REPLACE_SEASONAL_PRICING_DELETE_PATH]";
export const DEFAULT_SEASONAL_PRICING_DELETE_PATH = `${SEASONAL_PRICING_BASE_PATH}/Delete`;
export const SEASONAL_PRICING_DELETE_PATH = resolveReplaceable(
  RAW_SEASONAL_PRICING_DELETE_PATH,
  DEFAULT_SEASONAL_PRICING_DELETE_PATH
);

export const RAW_SEASONAL_PRICING_GET_LIST_PATH =
  "[REPLACE_SEASONAL_PRICING_GET_LIST_PATH]";
export const DEFAULT_SEASONAL_PRICING_GET_LIST_PATH = `${SEASONAL_PRICING_BASE_PATH}/GetList`;
export const SEASONAL_PRICING_GET_LIST_PATH = resolveReplaceable(
  RAW_SEASONAL_PRICING_GET_LIST_PATH,
  DEFAULT_SEASONAL_PRICING_GET_LIST_PATH
);

export const SEASONAL_PRICING_ENDPOINTS = {
  BASE_PATH: SEASONAL_PRICING_BASE_PATH,
  POST: SEASONAL_PRICING_POST_PATH,
  PUT: SEASONAL_PRICING_PUT_PATH,
  DELETE: SEASONAL_PRICING_DELETE_PATH,
  GET_LIST: SEASONAL_PRICING_GET_LIST_PATH,
};

// ================================
// ROOM SEASONAL PRICING ENDPOINTS
// ================================
export const RAW_ROOM_SEASONAL_PRICING_BASE_PATH =
  "[REPLACE_ROOM_SEASONAL_PRICING_BASE_PATH]";
export const DEFAULT_ROOM_SEASONAL_PRICING_BASE_PATH =
  "/hpms/api/RoomSeasonalPricing";
export const ROOM_SEASONAL_PRICING_BASE_PATH = resolveReplaceable(
  RAW_ROOM_SEASONAL_PRICING_BASE_PATH,
  DEFAULT_ROOM_SEASONAL_PRICING_BASE_PATH
);

export const RAW_ROOM_SEASONAL_PRICING_POST_PATH =
  "[REPLACE_ROOM_SEASONAL_PRICING_POST_PATH]";
export const DEFAULT_ROOM_SEASONAL_PRICING_POST_PATH = `${ROOM_SEASONAL_PRICING_BASE_PATH}/Post`;
export const ROOM_SEASONAL_PRICING_POST_PATH = resolveReplaceable(
  RAW_ROOM_SEASONAL_PRICING_POST_PATH,
  DEFAULT_ROOM_SEASONAL_PRICING_POST_PATH
);

export const RAW_ROOM_SEASONAL_PRICING_PUT_PATH =
  "[REPLACE_ROOM_SEASONAL_PRICING_PUT_PATH]";
export const DEFAULT_ROOM_SEASONAL_PRICING_PUT_PATH = `${ROOM_SEASONAL_PRICING_BASE_PATH}/Put`;
export const ROOM_SEASONAL_PRICING_PUT_PATH = resolveReplaceable(
  RAW_ROOM_SEASONAL_PRICING_PUT_PATH,
  DEFAULT_ROOM_SEASONAL_PRICING_PUT_PATH
);

export const RAW_ROOM_SEASONAL_PRICING_DELETE_PATH =
  "[REPLACE_ROOM_SEASONAL_PRICING_DELETE_PATH]";
export const DEFAULT_ROOM_SEASONAL_PRICING_DELETE_PATH = `${ROOM_SEASONAL_PRICING_BASE_PATH}/Delete`;
export const ROOM_SEASONAL_PRICING_DELETE_PATH = resolveReplaceable(
  RAW_ROOM_SEASONAL_PRICING_DELETE_PATH,
  DEFAULT_ROOM_SEASONAL_PRICING_DELETE_PATH
);

export const RAW_ROOM_SEASONAL_PRICING_GET_LIST_PATH =
  "[REPLACE_ROOM_SEASONAL_PRICING_GET_LIST_PATH]";
export const DEFAULT_ROOM_SEASONAL_PRICING_GET_LIST_PATH = `${ROOM_SEASONAL_PRICING_BASE_PATH}/GetList`;
export const ROOM_SEASONAL_PRICING_GET_LIST_PATH = resolveReplaceable(
  RAW_ROOM_SEASONAL_PRICING_GET_LIST_PATH,
  DEFAULT_ROOM_SEASONAL_PRICING_GET_LIST_PATH
);

export const ROOM_SEASONAL_PRICING_ENDPOINTS = {
  BASE_PATH: ROOM_SEASONAL_PRICING_BASE_PATH,
  POST: ROOM_SEASONAL_PRICING_POST_PATH,
  PUT: ROOM_SEASONAL_PRICING_PUT_PATH,
  DELETE: ROOM_SEASONAL_PRICING_DELETE_PATH,
  GET_LIST: ROOM_SEASONAL_PRICING_GET_LIST_PATH,
};

// ================================
// OWNER ENDPOINTS
// ================================
export const RAW_OWNER_BASE_PATH = "[REPLACE_OWNER_BASE_PATH]";
export const DEFAULT_OWNER_BASE_PATH = "/hpms/api/Owner";
export const OWNER_BASE_PATH = resolveReplaceable(
  RAW_OWNER_BASE_PATH,
  DEFAULT_OWNER_BASE_PATH
);

export const RAW_OWNER_POST_PATH = "[REPLACE_OWNER_POST_PATH]";
export const DEFAULT_OWNER_POST_PATH = `${OWNER_BASE_PATH}/Post`;
export const OWNER_POST_PATH = resolveReplaceable(
  RAW_OWNER_POST_PATH,
  DEFAULT_OWNER_POST_PATH
);

export const RAW_OWNER_PUT_PATH = "[REPLACE_OWNER_PUT_PATH]";
export const DEFAULT_OWNER_PUT_PATH = `${OWNER_BASE_PATH}/Put`;
export const OWNER_PUT_PATH = resolveReplaceable(
  RAW_OWNER_PUT_PATH,
  DEFAULT_OWNER_PUT_PATH
);

export const RAW_OWNER_DELETE_PATH = "[REPLACE_OWNER_DELETE_PATH]";
export const DEFAULT_OWNER_DELETE_PATH = `${OWNER_BASE_PATH}/Delete`;
export const OWNER_DELETE_PATH = resolveReplaceable(
  RAW_OWNER_DELETE_PATH,
  DEFAULT_OWNER_DELETE_PATH
);

export const RAW_OWNER_GET_LIST_PATH = "[REPLACE_OWNER_GET_LIST_PATH]";
export const DEFAULT_OWNER_GET_LIST_PATH = `${OWNER_BASE_PATH}/GetList`;
export const OWNER_GET_LIST_PATH = resolveReplaceable(
  RAW_OWNER_GET_LIST_PATH,
  DEFAULT_OWNER_GET_LIST_PATH
);

export const OWNERS_ENDPOINTS = {
  BASE_PATH: OWNER_BASE_PATH,
  POST: OWNER_POST_PATH,
  PUT: OWNER_PUT_PATH,
  DELETE: OWNER_DELETE_PATH,
  GET_LIST: OWNER_GET_LIST_PATH,
};

const ENDPOINTS_WITH_USERS = {
  ...BASE_ENDPOINTS,
  USERS: USERS_ENDPOINTS,
  USER_ROLES: USER_ROLES_ENDPOINTS,
  GUESTS: GUESTS_ENDPOINTS,
  OWNERS: OWNERS_ENDPOINTS,
  ROOMS: ROOMS_ENDPOINTS,
  ROOM_TYPES: ROOM_TYPES_ENDPOINTS,
  PROPERTY_TYPES: PROPERTY_TYPES_ENDPOINTS,
  PROPERTIES: PROPERTIES_ENDPOINTS,
  PROPERTY_AMENITIES: PROPERTY_AMENITIES_ENDPOINTS,
  ROOM_AMENITIES: ROOM_AMENITIES_ENDPOINTS,
  SEASONAL_PRICING: SEASONAL_PRICING_ENDPOINTS,
  ROOM_SEASONAL_PRICING: ROOM_SEASONAL_PRICING_ENDPOINTS,
};

export const ENDPOINTS = ENDPOINTS_WITH_USERS;
